apiVersion: v2
appVersion: 4.31.0
description: A Helm chart for creating a Selenium grid server in Kubernetes
home: https://github.com/DeathByMisadventure/selenium-helm
name: selenium-grid
type: application
version: 4.31.0
dependencies: []
