{{- if .Values.firefoxNode.enabled }}
{{- if .Values.firefoxNode.enableHPA }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "seleniumGrid.firefoxNode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: &chrome_node_labels
    app: selenium-chrome-node
    app.kubernetes.io/name: selenium-chrome-node
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.firefoxNode.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "seleniumGrid.firefoxNode.fullname" . }}
  minReplicas: 1
  maxReplicas: {{ .Values.firefoxNode.maxNodesHPA }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
{{- end  }}
{{- end  }}